### PR TITLE
Fix #12

### LINKED ISSUE #12: Spurious lib/libdeflate.h header file in lib directory
Since 1420c422e7ed35652f117ceb5f1407af237aa9e3, this line in _build.sh_:

```sh
# Redundant for linux. Necessary for Mac OS X.
 cp libdeflate.* $PREFIX/lib/
```

copies an extra copy of _libdeflate.h_ into the **lib** directory. Now that you're using `make install`, this `cp` command should be revisited — it seems likely that it can be dropped, or at least made more specific.

### PR DESCRIPTION
**Pull request by dpryan79**
Fix issue #12 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
I wonder if we need to copy the dylibs manually, since it looks like `make install` should be handling that.

**Comment by dpryan79** [comment]
@conda-forge/libdeflate Any objections? It seems that `make install` is installing everything properly these days, so this will clean up the random extra header under `$PREFIX/lib` reported in #12

**Review by rhpvorderman — APPROVED** [review]
Since all the tests succeed we can assume that this is safe. Maybe verify on a mac just to be sure? With some samtools command? (I do not have access to a mac).

**Comment by dpryan79** [comment]
I don't have one either, I'm also not entirely sure how to get a link to the artifacts in conda-forge.

**Comment by rhpvorderman** [comment]
Well, I propose we wait on @hmaarrfk and if he also does not have access to one I suggest we merge. The tests on Mac succeed so we have done all the validation we can do.

**Comment by hmaarrfk** [comment]
Thanks you two!

**Comment by hmaarrfk** [comment]
If any of you want to help maintain this, please make a PR adding yourselves to the repo!

**Comment by jmarshall** [comment]
Feel free to loop in the author of #12, who does have a Mac :smile:

Confirmed that _osx-64/libdeflate-1.7-h35c211d_5.tar.bz2_, just uploaded, contains all the files expected — the only difference in the file listing from 1.7-…_4 is the removal of the spurious _lib/libdeflate.h_, as expected.

**Comment by hmaarrfk** [comment]
haha, the auto closing and cross referencing of github issues typically helps with that.

often i find that getting cc'ed cuases extra noise.

**Pull request merged**
